name = "chief/dependencies"
version = "0.1.0-canary.1"
description = "The Dependencies extension for Chief: topological dependency injection."
authors = ["ryancundiff"]
repository = "https://github.com/ryancundiff/chief"
license = "MIT"
includes = ["src/*", "LICENSE", "README.md", "pesde.toml"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
core = { workspace = "chief/core", version = "^" }
